version: '2'

services:
  postgres:
    image: acrarolibotnonprod.azurecr.io/geo-catalog:v1.0.7
    ports:
      - '8080:8080'
    environment:
      - DB_PASSWORD=Libot4allnonprod
      - DB_USERNAME=postgres
      - POSTGRES_DB=catalog
      - ALLOW_EMPTY_PASSWORD=true
      - DB_HOST=10.0.4.4
      - DB_PORT=5432
