{{- $chartName := include "geoCatalog.name" . -}}
{{- $tracingUrl := include "geoCatalog.tracingUrl" . -}}
{{- $metricsUrl := include "geoCatalog.metricsUrl" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  DB_HOST: {{ quote .Values.db.host }}
  DB_PORT: {{ quote .Values.db.port }}
  DB_NAME: {{ .Values.db.database }}
  DB_PASSWORD: {{ .Values.db.password }}
  DB_USERNAME: {{ .Values.db.username }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  npm_config_cache: /tmp/
{{- end }}
