global:
  environment: {}
  cloudProvider: {}
  metrics: {}
  tracing: {}

image:
  repository: "geo-catalog"
  tag: "v1.0.7"

enabled: true
environment: "development"
initialDelaySeconds: 60
nodePort: 30030
replicaCount: 1

cloudProvider:
  dockerRegistryUrl: "acrarolibotnonprod.azurecr.io"
  flavor: "openshift"
  imagePullSecretName: ""
  
authentication:
  ssl:
    enabled: false
    useExternal: false
    externalSecretName: ""

route:
  enabled: true
  path: /
  timeout:
    enabled: false 
    duration: 60s 

ingress:
  enabled: false
  type: 'nginx-org'
  path: /
  host: "localhost"
  cors:
    enabled: true
    origin: '*'

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  tracing:
    enabled: false
    url: "http://localhost:55681/v1/trace"
  metrics:
    enabled: false
    url: "http://localhost:55681/v1/metrics"
  requestPayloadLimit: 1mb

resources:
  enabled: true
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

db:
  host: 10.0.4.4
  port: 5432
  username: postgres
  password: Libot4allnonprod
  database: catalog
